### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 26 March 2024

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#189]
## Date

Tuesday 26 Mar 2024 - 11:00 EST / 15:00 UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people (@dc-ms) (5mins)
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-automation/issues/184) (@dc-ms) (1min)
- [x] Recap of [On-Site Accelerator](https://github.com/finos/devops-automation/issues/185) (@willosborne) (5min)
- [x] Updates on recent developments
  - [x] Validator Validator (@willosborne) (5min)
  - [x] Translator: C4 (@Budlee) / k8s (@matthewgardner) (5min)
  - [x] Visualizer (@aidanm3341) (5min)
- [x] [Proposed CLI](https://github.com/finos-labs/architecture-as-code/issues/53) (@grahampacker-ms / @willosborne) (5min)
- [x] Proposal to introduce 'conceptual' architecture patterns / blueprints (Frank Schawillie) (10min)
- [ ] Overview of [C4InterFlow](https://github.com/SlavaVedernikov/C4InterFlow); how does this complement / converge with CALM? (@SlavaVedernikov) (10min)
- [x] Where should we keep our meeting agendas / minutes? Whilst we're part of the DevOps Automation SIG we now have our own repo where we're building out CALM and associated capabilities. Should we move our meeting minutes and agendas to that repo to avoid confusion? (@dc-ms) (2min)
- [ ] Review of issues, AOB (@dc-ms) (7min)

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by Budlee** [comment]
Matthew Auburn / Morgan Stanley

**Comment by grahampacker-ms** [comment]
Graham Packer / Morgan Stanley

**Comment by dc-ms** [comment]
Denis Coffaro / Morgan Stanley

**Comment by willosborne** [comment]
Will Osborne / Morgan Stanley

**Comment by aidanm3341** [comment]
Aidan McPhelim / Morgan Stanley

**Comment by lbulanti-ms** [comment]
Luigi Bulanti / Morgan Stanley

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by SlavaVedernikov** [comment]
Slava Vedernikov / Solutions Unit

**Comment by lionking421** [comment]
Prashant Jasani / Morgan Stanley

**Comment by fleureedwards** [comment]
Fleur Edwards / Nomura

**Comment by ojeb2** [comment]
Oli Bage / LSEG

**Comment by aldwins-ln** [comment]
Aldwin Saugere / Morgan Stanley

**Comment by karlmoll** [comment]
Also attended:

Louis Paul / Prudential
Frank Schawillie / RBC
Shane Artis / Morgan Stanley

**Comment by matthewgardner** [comment]
Matthew Gardner / Morgan Stanley

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by rocketstack-matt** [comment]
**FINOS Meeting**: March 26, 2024 (courtesy @dc-ms)
 
**Commenced**: 11:05 EST
 
**Introduction / FINOS Disclaimer**: Completed

**Agenda & Attendance noted** : https://github.com/finos/devops-automation/issues/189 - Done
 
Previous minutes approved by attendees and closed out (Issue 184) : https://github.com/finos/devops-automation/issues/184 - Done

**On Site Accelerator Recap**:  @willosborne 
* Movement to meta schema 
* API Gateway Pattern 
* Demo with IntelliJ with auto-complete
* Visualization – VSCode extension via Mermaid – @aidanm3341 
* Visualization – Java CALM schema using Structurizr tooling into C4
* Spectral
* Design – composable interfaces while managing complexity 
* Control requirements – governance over patterns 
                                                                
**Recent Developments**: @willosborne  / @matthewgardner  / @aidanm3341  / @Budlee 
**Validator**: 
* Spectral integration & AJV tool 
* Instantiation of a pattern and the pattern itself validations
*  Backwards compatibility to what degree or release fixed
**C4 Translator**
* Extending to k8s
**Visualizer**:
* Embedded in CLI

**Proposed CLI**: @grahampacker-ms  / @willosborne 
* Generation of pattern from schema
* Validation of pattern (JSON schema and Spectral)
* Output of SVG
* Typescript and Node                                                             

**Conceptual Patterns**: Frank Schawillie
* Presenting his AaC project
* Highlighting a view of controls mapping to architecture
* Spoke on scope definition and managing simplicity 

**C4Interflow**: @SlavaVedernikov 
* Brief demo but an additional session is requested
                                                                
**Admin Tasks**:
* Where do we keep meeting agendas/minutes?
  * Let’s move to everything to our current repo. No objections.


**Issues**: https://github.com/finos-labs/architecture-as-code/issues 


**Adjourned**: 12:10 EST

**Comment by rocketstack-matt** [comment]
Approved at #194
