### ISSUE TITLE
DevOps Automation SIG Meeting - Feb 16, 2023

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-automation#69]
## Date

Thursday, Feb 16 2023 - 12pm ET; 5pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-automation/issues/68)
- [x] SIG working group updates and proposed engagement model
    - [x] [Backstage in Financial Services](https://github.com/finos/devops-automation/issues/71)
    - [x] Managing open source supply chain risks  
    - [x] [Enabling automated change deployment](https://github.com/finos/devops-automation/issues/72)
- [x] AOB, Q&A & Adjourn (5mins)
  - FINOS All Community Call : DevOps Automation named as top 3 FINOS initiative because they are organisationally strategic.

![2023 Q1 - FINOS All Community Call ](https://user-images.githubusercontent.com/6029572/219412945-2d1afd0d-5483-43e5-8798-95178550c5d6.jpg)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info

**Webex:**
https://finos.webex.com/finos/j.php?MTID=md62056638ba05fbea86b9582df94f807

### Dial-in

- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 662 6070

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by cnygardtw** [comment]
Backstage workstream engagement model here: https://github.com/finos/devops-automation/issues/71

**Comment by ashukla13** [comment]
Amol from Morgan Stanley

**Comment by mcleo-d** [comment]
Hi there 👋🏻

**Comment by brunon** [comment]
hello!
